### ISSUE TITLE
CIO Does not account for being in a directory that does not exist.

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#434]
If you are in a branch with a valid directory, change to a branch where that directory does not exist, attempting to use CIO in that directory will break rather than elegantly inform the user that the directory does not exist.

```
path.js:1165
        path = process.cwd();
                       ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1165:24)
    at Function.Module._resolveLookupPaths (module.js:424:17)
    at Function.Module._resolveFilename (module.js:542:20)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/joshua/.nvm/versions/node/v8.16.0/lib/node_modules/check-it-out/index.js:3:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

```

**Comment by jwu910** [comment]
Can't seem to reproduce...
